package com.kat.backend.moderation.entity;

public enum ModerationRuleType {
    SPAM, LINKS, INVITES, MENTIONS, CAPS,
    REPETITION, WALL_OF_TEXT, NEWLINES, SPOILERS, EVERYONE_HERE,
    FORMATTING, EMOJIS, BAD_WORDS, PHISHING, MASS_MENTION,
    IMAGE_SPAM, COPY_PASTA, ACCOUNT_AGE, JOIN_RAID, CHANNEL_RAID, ROLE_RAID
}